# Generated by Django 3.2.8 on 2022-06-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.CharField(max_length=200)),
                ('page_id', models.CharField(max_length=200)),
                ('instagram_id', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('graph_domain', models.CharField(default='https://graph.facebook.com', max_length=200)),
                ('graph_version', models.CharField(default='v14.0', max_length=200)),
                ('endpoint_base', models.CharField(default='https://graph.facebook.com/v14.0/', max_length=200)),
            ],
        ),
    ]
