# Generated by Django 3.2.8 on 2022-06-16 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('day', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('story_count', models.CharField(max_length=200)),
                ('carousel_count', models.CharField(max_length=200)),
                ('media_count', models.CharField(max_length=200)),
                ('media_likes', models.CharField(max_length=200)),
                ('media_comments', models.CharField(max_length=200)),
                ('media_reach_impressions', models.CharField(max_length=200)),
                ('story_reach_impressions', models.CharField(max_length=200)),
                ('carousel_reach_impressions', models.CharField(max_length=200)),
                ('account_reach_impressions', models.CharField(max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='main.account')),
            ],
        ),
    ]
