# Generated by Django 3.2.8 on 2022-06-28 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_account_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insights',
            new_name='Insight',
        ),
    ]
